---
title: "ExperimentOne"
author: "Jenna Register"
date: "January 27, 2017"
output: html_document
---

## Experiment One

Here we will be analyzing how well Churiso can capture human behavior in the "Marvin the Robot" tasks. 

```{r}
library(ggplot2)
library(plyr)
library(dplyr)
```

## Checking out the Human Data
```{r}
human = read.csv("human.csv", header=TRUE)
colnames(human) = c("answer","generalization","probability","condition")

#what does the human data look like?
human$generalization <- gsub(" ","",human$generalization)
humplt = ggplot(human, aes(answer, probability, fill=as.factor(condition)))+
  geom_bar(stat="identity")+
  facet_grid(~generalization~condition)
humplt

#put the human frame into the form of the model frame
hp <- human %>% arrange(generalization) %>% as.data.frame()
hp <- hp[,c(2,4,1,3)]

hp

```

##Working With Overall Correlations##
```{r fig.width=15, fig.height=7}
#plot the overall correlations
correlations = read.csv("correlations.csv")
correlations$Legend = "Lower than .4"
correlations$Legend[correlations$Kendall>.4]="Higher than .4"

correlations =correlations[order(-correlations$Kendall),]
correlations = correlations[1:100,]
#View(correlations)

plt = ggplot(correlations,aes(Basis,Kendall,fill=Legend))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle=60, hjust=1))
  
plt
#ggsave("Correlations.pdf" ,plt,width=10)

```


##Working With Correlations by Condition##
```{r fig.width=15, fig.height=7}
#plot the correlations by condition
cond_correlations = read.csv("condition_cors.csv")
cc <- cond_correlations %>%
 
                    group_by(condition) %>%
                    arrange(condition,desc(cor)) %>%
                    top_n(n=10, wt=cor)


plt = ggplot(cc,aes(basis,cor, fill=as.factor(condition)))+
  geom_bar(stat="identity")+
  facet_grid(~condition, scales="free",space="free")+
  
  theme(axis.text.x = element_text(angle=60, hjust=1))

plt
#ggsave("Correlation_by_Condition.pdf", plt, width=10, height=4)

```

##Are We Doing Better Than Random?##
```{r}
maxes = list()
max_ks = list()

max_by_cond = NULL

```

```{r loop}

for (i in 0:100){
  #initialize the correlations table
  correlations = data.frame(Basis=character(),Correlation=double(),Kendall=double())
  #faceted_cors = data.frame(Condition=integer(),Correlation=double(),Basis=character())
  #we need to test if our model is doing any better than random...
  #let's scramble! (shuffles by condition and generalization)
  
  scrambled <- hp %>%
    group_by(condition, generalization) %>%
    mutate(probability=sample(probability))
  
  
  #now compare all the model bases to this scramble!
  for(f in list.files("ag/", full.names=TRUE)) {
   
      ag <- read.csv(f, header=TRUE)
      name = gsub("ag/output", "",f)
      
      # what if our probability was proportional to the runtime
      
      
        #saving the correlations to a dataframe
        c = cor.test(scrambled$probability,ag$modprobability)
        k = cor.test(scrambled$probability,ag$modprobability,method="kendall")
        
        correlations <-rbind(correlations,data.frame(Basis=name,Correlation=c$estimate, Kendall=k$estimate))
        
        
        #cors <- ddply(na.omit(scrambled), c("condition"), summarise, cor = round(cor(scrambled$probability, ag$modprobability), 2))
        #cors$basis = name
        
        #put together the correlations by condition
        #faceted_cors = rbind(faceted_cors,cors)
        
       #View(faceted_cors)

  }
  
  m = max(correlations$Correlation)
  mk = max(correlations$Kendall)
  maxes<-append(maxes,m)
  max_ks <-append(max_ks,mk)
  
  
  #m_by_cond <- na.omit(faceted_cors) %>%
                #group_by(condition, basis) %>%
                #mutate(MaxCor = max(cor))
  
  
  
  
      
}

```

```{r}
#Take a look at an example scrambled frame (technically, the last one called in the loop)
scrambled

#Take a look at an example ag frame (technically, the last one called in the loop)
ag

mc_before<-data.frame(unlist(maxes))
names(mc_before) <-c("MaxCorrelations")
write.csv(mc_before,"MaxCorrelations.csv")
mk_before<-data.frame(unlist(max_ks))
names(mk_before) <-c("MaxKendalls")
write.csv(mk_before,"MaxKendalls.csv")


#write.csv(m_by_cond,"Max_By_Condition.csv")
```

```{r readin}
#the human correlations
correlations=read.csv("correlations.csv",header=TRUE)

```

```{r}
#maximum correlations to random
mc = read.csv("MaxCorrelations.csv",header=TRUE)

```

```{r}
#maximum kendalls
mk = read.csv("MaxKendalls.csv", header=TRUE)

```


##Let's take a look at the distribution of max correlations now!##

```{r fig.width=7}

plt = ggplot(mc, aes(x=MaxCorrelations)) + geom_density() +
  xlab("Correlation")+
  ggtitle("Model to Random Scramble (Correlation)")
plt
```

```{r}
#maximum kendalls to random
plt = ggplot(mk, aes(x=MaxKendalls)) + geom_density()+xlab("Kendall Tau") + ggtitle("Model to Random Scramble (Kendall)")
plt
```

```{r}
#HUMAN COR.TESTS
plt = ggplot(correlations, aes(x=Correlation)) +
  geom_density() +
  ggtitle("Model to Human Data (Correlation)")+
  geom_density(data=mc,aes(x=MaxCorrelations),color="blue")
  
plt

```

```{r}
#HUMAN KENDALL TAUS
plt = ggplot(correlations, aes(x=Kendall)) + geom_density()+ggtitle("Model to Human Data (Kendall)")
plt

```

```{r}
plt = ggplot(mc, aes(x=MaxCorrelations)) + 
  geom_density()+
  ggtitle("Distribution of Correlations to Random Data")+
  geom_vline(data = correlations, aes(xintercept = max(correlations$Correlation),color="red"),linetype="dashed")+
  geom_text(aes(x=max(correlations$Correlation)-.02, label="Maximum Model Correlation to Human Data", y=3,angle=90))+
  theme(legend.position="none")
  
plt
```



```{r p vals}
mc$Better = FALSE
mc$Better[mc$m >= max(correlations$Correlation)] = TRUE

num = length(mc$Better[mc$Better==TRUE]) #number of better than REAL human max correlation
denom = length(mc$Better)#number of worse than REAL human max correlation

#p val for cor.test
num/length(mc$Better)


mk$Better = FALSE
mk$Better[mk$MaxKendalls >= max(correlations$Kendall)] = TRUE


numk = length(mk$Better[mk$Better==TRUE]) #number of better than REAL human max correlation
denomk = length(mk$Better)#number of worse than REAL human max correlation

#pval for Kendall Tau
numk/length(mk$Better)
```


