#for b in 'GSKH' 'GSKHI' 'GSKHIE' 'GBMWCESKHI' 'GSK' 'GSKI' 'GSKIE' 'GBMWC' 'GBMWCE' 'GTSKH' 'GTSKHI' 'GTSKHIE' 'GTBMWCESKHI' 'GTSK' 'GTSKI' 'GTSKIE' 'GTBMWC' 'GTBMWCE' 'SKH' 'SKHI' 'SKHIE' 'BMWCESKHI' 'SK' 'SKI' 'SKIE' 'BMWC' 'BMWCE' 'TSKH' 'TSKHI' 'TSKHIE' 'TBMWCESKHI' 'TSK' 'TSKI' 'TSKIE' 'TBMWC' 'TBMWCE'
for b in 'S' 'K' 'I' 'H' 'G' 'E' 'T' 'M' 'B' 'C' 'SKI' 'IHGE' 'IHGT' 'IHGM' 'IHGB' 'IHGC' 'IHET' 'IHEM' 'IHEB' 'IHEC' 'IHTM' 'IHTB' 'IHTC' 'IHMB' 'IHMC' 'IHBC' 'IGET' 'IGEM' 'IGEB' 'IGEC' 'IGTM' 'IGTB' 'IGTC' 'IGMB' 'IGMC' 'IGBC' 'IETM' 'IETB' 'IETC' 'IEMB' 'IEMC' 'IEBC' 'ITMB' 'ITMC' 'ITBC' 'IMBC' 'HGET' 'HGEM' 'SKIHGEMBC' 'SKIHGTMBC' 'SKIHETMBC' 'SKIGETMBC' 'SKHGETMBC' 'SIHGETMBC' 'KIHGETMBC' 'SKIHGETMBC'
do
    nohup pypy pure-relations-nogs.py --search-basis=$b --max-depth=9 > model-outputs2/$b.txt 2>> err.txt &
done
